version: '3.4'

services:
  dockerapitest:
    image: hakart/dockerapitest:test-${BUILD_NUMBER}
    build:
      context: .
      dockerfile: DockerAPITest\Dockerfile
    ports:
      - "5000${BUILD_NUMBER}:80"
    
    