version: '3.4'

services:
  dockerapitest:
    image: hakart/dockerapitest:test-${BUILD_NUMBER}
    build:
      context: .
      dockerfile: DockerAPITest\Dockerfile
    ports:
      - "50000:80"
    
  nunittest:
    image: hakart/nunittest:test-${BUILD_NUMBER}        
    build:
      context: .
      dockerfile: NUnitTest\Dockerfile